name:                type-sandbox
version:             0.1.0.0
homepage:            https://github.com/githubuser/tapl#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
extra-source-files:
- README.md

default-extensions:
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - LambdaCase
  - PatternSynonyms
  - OverloadedStrings
  - NamedFieldPuns
  - ConstraintKinds

dependencies:
  - base >= 4.7 && < 5
  - containers
  - free
  - haskeline
  - lens
  - megaparsec
  - recursion-schemes
  - text
  - mtl

ghc-options: -Wall

executables:
  fomega:
    source-dirs:
      - src
      - app
    main: FOmega/Repl.hs
  pi-repl:
    source-dirs:
      - src
      - app
    main: Dependent/Repl.hs
  systemf:
    source-dirs:
      - src
      - app
    main: SystemF/Repl.hs
