name:                type-sandbox
version:             0.1.0.0
homepage:            https://github.com/githubuser/tapl#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
extra-source-files:
- README.md

default-extensions:
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - LambdaCase
  - PatternSynonyms
  - OverloadedStrings
  - NamedFieldPuns
  - ConstraintKinds

dependencies:
  - base >= 4.7 && < 5
  - free
  - recursion-schemes
  - haskeline
  - megaparsec
  - text
  - containers

ghc-options: -Wall

library:
  source-dirs:      src
